id: PD5E43F45
initial_creation_type: ocr
source_metadata:
  volumes:
    d6ac00a5dd4a4859b1a50cfe87f985d8:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: རྗེ་བཙུན་འཕགས་པ་འཇམ་དཔལ་གྱི་སྙིང་རྗེ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
